name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  buildss:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-liner script
        run: echo "Testing, its the first step!"

      - name: Print hostname
        run: hostname
